baseURL = "https://kepulsary.github.io/"
defaultContentLanguage = "zh"
title = "KePulsary"
theme = "hugo-theme-stack"
hasCJKLanguage = true
enableEmoji = true

[pagination]
pagerSize = 10

[permalinks]
  page = "/:slug/"
  posts = "/:year/:month/:day/:filename/"

[frontmatter]
lastmod = ["lastmod", "updated", ":git", "date"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    noClasses = false
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      taskList = true
      strikethrough = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    [menu.main.params]
      Icon = "home"
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 5
    [menu.main.params]
      Icon = "archives"
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 10
    [menu.main.params]
      Icon = "tag"
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 15
    [menu.main.params]
      Icon = "search"
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 20
    [menu.main.params]
      Icon = "user"

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/KePulsary"
    weight = 1
    [menu.social.params]
      Icon = "brand-github"

[params]
mainSections = ["posts"]
favicon = "/favicon.ico"
description = "AI & Security"

  [params.footer]
    since = 2021

  [params.dateFormat]
    published = "2006-01-02"
    lastUpdated = "2006-01-02"

  [params.sidebar]
    subtitle = "AI & SEC"
    avatar = "img/avatar.jpg"

  [params.article]
    math = false
    readingTime = true
    autoCover = false
    [params.article.license]
      enabled = false

  [params.widgets]
    [[params.widgets.homepage]]
      type = "search"
    [[params.widgets.homepage]]
      type = "archives"
      limit = 5
    [[params.widgets.homepage]]
      type = "tag-cloud"
      limit = 10
    [[params.widgets.page]]
      type = "toc"

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.comments]
    enabled = false

  [params.opengraph.twitter]
    card = "summary_large_image"
